### ISSUE TITLE
Inconsistent check regarding static actors

### ISSUE THREAD

**Issue by razfriman** [xNocken/replay-reader#12]
Had a read through to help teach myself a bit more about static actors and bumped into this check which seems to not be a valid check for `isNumber` since the `||` will allow many many many conditions.

https://github.com/xNocken/replay-reader/blob/d1622a23dbb5928fa2f5597fb2f41a8b049617bb/src/utils/clean-static-id-suffix.ts#L3

**Comment by xNocken** [comment]
Yeah you're right. that statement sees every character as a number. Funnily enough i fixed that a few days ago and commited it on the same day you opened the issue.
