### ISSUE TITLE
If player is a bot, BotUniqueId is empty

### ISSUE THREAD

**Issue by dblythy** [xNocken/replay-reader#9]
Thanks for your awesome work on this project.

I am having an issue getting Bot player IDs.

If a player is a bot, they do not have a "UniqueId" property, instead it's "BotUniqueId".

I can't work out how to get "BotUniqueId" to pass. If I replace [this line](https://github.com/xNocken/replay-reader/blob/caae8b8a2204d3a402f870bc20a285d4b100be4e/NetFieldExports/FortPlayerState.json#L16) with BotUniqueId, the BotUniqueId's come through, but not the real PlayerIds.

Any suggestions @xNocken?

Thanks!

**Comment by xNocken** [comment]
You need to have both entries if you want both to export. Overriding the playerId with the botId removes the playerId. So just add both like this.

```json
{
  "UniqueId": {
    "name": "UniqueId",
    "type": "string",
    "parseFunction": "readNetId",
    "parseType": "default"
  },
  "BotUniqueId": {
    "name": "BotUniqueId",
    "type": "string",
    "parseFunction": "readNetId",
    "parseType": "default"
  }
}
```

**Comment by dblythy** [comment]
I tried that as well, and BotUniqueId will never output. The only way I could get it to output was by using UniqueId

**Comment by xNocken** [comment]
Just to be sure you did change both names right? The key and the name property?

**Comment by dblythy** [comment]
You're right - it seems I am the bot here

**Comment by xNocken** [comment]
Im glad i could solve your problem. And no you dont need to create a PR for this. It would just resolve in unnecessary merge conflicts with the new V2 branch. But i will be adding it myself. If you dont have any more questions feel free to close this issue

**Comment by dblythy** [comment]
Awesome. Excited for V2.
